### ISSUE TITLE
Feature Request: hoggle uninstall

### ISSUE THREAD

**Issue by alecbz** [sjansen/hoggle#1]
Minor, but would be nice to have a `hoggle uninstall` to undo `hoggle init`.

**Comment by sjansen** [comment]
Done. https://github.com/sjansen/hoggle/releases/tag/v0.1.1

Thanks for the feedback.

**Comment by alecbz** [comment]
Does this still need a call to `RootCmd.AddCommand` somewhere, like https://github.com/sjansen/hoggle/blob/5023649ec047ce26386b37328d579da177d5801c/cmd/init.go#L9 or https://github.com/sjansen/hoggle/blob/5023649ec047ce26386b37328d579da177d5801c/cmd/standalone.go#L10 ?

**Comment by sjansen** [comment]
:grimacing: Yes, sorry, I forgot to commit a file.

https://github.com/sjansen/hoggle/releases/tag/v0.1.2
